### ISSUE TITLE
Is there a way to push the Flow Chart to the top of the output.

### ISSUE THREAD

**Issue by StevenReid** [mozziemozz/M365CallFlowVisualizer#16]
At the moment, there is a lot of blank space at the top of the output.  is there a way to reduce this?

**Comment by mozziemozz** [comment]
I'm afraid not. I believe that this is caused by how mermaid renders diagrams. I think you can control it by adding maxwidth parameter at the top of the diagram but I don't have the exact command right now, sorry. It might crop the width of the diagram though.

**Comment by StevenReid** [comment]
Thanks for the confirmation.  and thanks for a very useful solution!
