### ISSUE TITLE
Call flow used for greeting only throws an error

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#17]
I built an attendant for the purposes of 'explaining that calls are unable to be answered, and asked for users to call-back later'.

EG:
AA Security > Queue 1 > Timeout 45s > Queue 2 > Timeout 135s > AA Security Unanswered

```
#Security Diagram
U:\Teams\M365CallFlowVisualizerV2.ps1 -VoiceAppName 'Security' -VoiceAppType 'Auto Attendant' -ShowTTSGreetingText -CustomFilePath U:\Teams\Diagrams

Getting call flow for: Security Unanswered
Voice App Id: 478da7f7-b9a8-4e43-8d22-9310bc0b00b8
ConvertTo-Csv : Cannot bind argument to parameter 'InputObject' because it is null.
At U:\Teams\M365CallFlowVisualizerV2.ps1:772 char:110
+ ... ect {$_.name -match "after"}).WeeklyRecurrentSchedule | ConvertTo-Csv
+                                                             ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertTo-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertToCsvCommand
```

**Comment by mozziemozz** [comment]
I think I also encountered this issue once. The problem was that somehow the business hours were not saved correctly in the AA Object. Please try to go to the AA in TAC, reset business hours and save again. If you can't save, change any setting save, revert the changed setting to your desired settings and save again.

**Comment by sjackson0109** [comment]
This issue was superseeded by issue #19 - closing
