### ISSUE TITLE
Get-CsTenant error 403

### ISSUE THREAD

**Issue by johnacook-123** [mozziemozz/M365CallFlowVisualizer#20]
Hi. I am getting this error when launching the script:

Get-CsTenant : Connecting to remote server api.interfaces.records.teams.microsoft.com failed with the following error
message : The WinRM client received an HTTP status code of 403 from the remote WS-Management service. For more
information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Get-CsTenant
+ ~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Get-CsTenant], PSRemotingTransportException
    + FullyQualifiedErrorId : System.Management.Automation.Remoting.PSRemotingDataStructureException,Microsoft.Teams.C
   onfigApi.Cmdlets.GetCsTenant

Any ideas?

**Comment by mozziemozz** [comment]
Which Teams Module Version are you using? It might be a temporary issue with Microsoft. Do other cmdlets e.g. Get-CsOnlineSipDomain or Get-CsOnlineUser work?

**Comment by johnacook-123** [comment]
I tried 3.0.0 and 4.0.0. Yes and get-cstenant works in the same shell, the error comes after auth when calling your function it seems. Thanks

**Comment by mozziemozz** [comment]
I killed my PS session and started a new one. Working again in VS Code integrated PS and also Windows Terminal PS.
