### ISSUE TITLE
Maximum text size in Diagram exceeded 

### ISSUE THREAD

**Issue by ElazarOhayon** [mozziemozz/M365CallFlowVisualizer#21]
Hi Martin heusser,

hope you doing well.

firest your script very helpful.
today I have exported a Big Auto attended.

after I tried  to see the Diagram I get - **Maximum text size in Diagram exceeded** 
![image](https://user-images.githubusercontent.com/55660350/159264329-f9f43030-9b83-49aa-8d10-0cffc1733dd9.png)

i found this solution here-
**https://github.com/mermaid-js/mermaid-cli/issues/113**

to change - 

{
    "maxTextSize" : 99999999
}

it's solved the issue.

please leave a note for everyone.

thanks ,

**Comment by mozziemozz** [comment]
Hi Elazar,

Thanks for the info. How did you fix it? Did you put maxTextSize directly into the *.md file? Can you please post an example so I can see if I can implement it for everybody?

**Comment by ElazarOhayon** [comment]
Hi Martin, 

In this website - 
[https://mermaid-js.github.io/mermaid-live-editor](url)

**in "Config" section -**

just add -
 {
"maxTextSize" : 99999999
}

![image](https://user-images.githubusercontent.com/55660350/159430071-00d166f5-c187-4019-860b-ee7da6f15e68.png)

**Comment by mozziemozz** [comment]
added to theme a while ago
