### ISSUE TITLE
Holiday title source

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#27]
Hello,

So i have the following setup as holiday dates.
![image](https://user-images.githubusercontent.com/38080190/187440987-fca9146e-417b-45b8-ab24-572e75f33dac.png)
I update last-years holidays, to next-years, sometime in January. 

Each of my call-flows (AAs) pulls in them in, as labelled LIST A and LIST B:
![image](https://user-images.githubusercontent.com/38080190/187441337-5974592a-4b9f-4489-9181-04c86e4f70b6.png)

Here is the diagram:
![image](https://user-images.githubusercontent.com/38080190/187442307-a8de28c6-1a1f-467b-b822-b9ad59598549.png)

Can I request you change the SOURCE of the title, to the holiday-list definition?

Thanks,

**Comment by mozziemozz** [comment]
Hi @sjackson0109, can't you just name your holiday call handlings the same as the org-wide holiday list? Or am I missing something here? The visualizer is always running under the context of a specific AA so it will display the name of the holiday call handling. 2 different AAs might use the same holiday list but use different names for the call handling. Let's assume you're looking at a diagram and then want to check this AA in TAC. Now the diagram only lists the name of the org-wide holiday list name, which you can't find on the AA itself...

What If I keep the call handling name as the subgraph title but add the name of the org-wide list as well? Would that help?

**Comment by sjackson0109** [comment]
Naming them is possible for year 1 and 2 - call it 2022 and 2023 for arguments sake.
When I update the holidays schedules (not the association-name of dozens of call-flows)..  then the naming will change and conflict.
Eg: in early Jan 2023, I have a task to update the national holidays (outlook reminder :p).. so I go ahead and update all the date inside the ‘UK National Holidays 2022’ to cover the year 2024, and also rename the schedule to ‘UK National Holidays 2024’.  At that point all the associated schedules in all my call flows will be called 2022, but the data inside the schedule is updated to 2024. Hence using the name A and B instead.

Perhaps the sub-graph name idea would work. But I suggest remove the name altogether on the holiday-schedule association layer. That might work.

**Comment by mozziemozz** [comment]
IIRC the schedule is read directly from the AA object. So I have to check if I can figure out which org-wide holiday list is used (make a connection between them). I will check if I can create a param switch for your request but I think I‘ll leave the default as it is because that‘s the name of the holiday call handling of the specific AA the script is running for. I‘ll have to check when I got some time for that though.

**Comment by mozziemozz** [comment]
Diagram now shows both the name of the Call Handling and the Name of the Schedule:
![image](https://user-images.githubusercontent.com/50239556/194504526-072a4b2b-9f5b-49ce-99db-7d5927bde226.png)
