### ISSUE TITLE
Multi-Tenancy Support

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#3]
Hello, I work for an MSP. and being able to assist customers/troubleshoot their configuration of their own call-flows would be sooo much easier, if we could choose the tenant (or specify the tenant ID) if possible.

Am assuming this is possible, as i can successfully perform PowerShell to 'loop through all customers/tenants to provide a CSV breakdown of their subscription licensing and assignment-totals'.

**Comment by mozziemozz** [comment]
Hi, Multi Tenancy is not supported currently. For now, you just have to connect to each tenant individually. Are you connecting with a dedicated admin from their tenant or using a delegated admin from your tenant?

**Comment by sjackson0109** [comment]
my user is inside a a Microsoft partner relationship (ie my own azure tenant); but we manage teams and PSTN for multiple tenants (customers).

Thanks

**Comment by mozziemozz** [comment]
If you can give me a little more information or an example code how to loop through multiple tenants I can take a look and see what I can do.

**Comment by sjackson0109** [comment]
This might help:
`#Establish a PowerShell session with Office 365. You'll be prompted for your Delegated Admin credentials
Import-Module MSOnline
Connect-MsolService
$customers = Get-MsolPartnerContract -All
Write-Host "Found $($customers.Count) customers for $((Get-MsolCompanyInformation).displayname)." -ForegroundColor DarkGreen
$CSVpath = "C:\Temp\O365\"
  
foreach ($customer in $customers) {
    Write-Host "Retrieving license info for $($customer.name)" -ForegroundColor Green
    $CSVClientpath = $CSVpath + $($customer.name) + "-report.csv"
    $licensedUsers = Get-MsolUser -TenantId $customer.TenantId -All | Where-Object {$_.islicensed}
  
    foreach ($user in $licensedUsers) {
        Write-Host "$($user.displayname)" -ForegroundColor Yellow  
        $licenses = $user.Licenses
        $licenseArray = $licenses | foreach-Object {$_.AccountSkuId}
        $licenseString = $licenseArray -join ", "
        Write-Host "$($user.displayname) has $licenseString" -ForegroundColor Blue
        $licensedSharedMailboxProperties = [pscustomobject][ordered]@{
            CustomerName      = $customer.Name
            DisplayName       = $user.DisplayName
            Licenses          = $licenseString
            TenantId          = $customer.TenantId
            UserPrincipalName = $user.UserPrincipalName
        }
        $licensedSharedMailboxProperties | Export-CSV -Path $CSVClientpath -Append -NoTypeInformation   
    }
}`

**Comment by mozziemozz** [comment]
3.0.11 now supports sign in via Entra ID Appregistration and you must specify a Tenant ID. You must either have an Entra ID App  registration in each tenant or create a multi tenant app and add it to each tenant. Also make sure to disconnect Teams and graph before you run it for another tenant.

I don't have the capacity to write a tenant looping script right now, sorry.
