### ISSUE TITLE
npm install -g @mermaid-js/mermaid-cli

### ISSUE THREAD

**Issue by dinocaputo** [mozziemozz/M365CallFlowVisualizer#31]
I get an error when running this cmdlet

PS C:\Users\dcaputo> npm install -g @mermaid-js/mermaid-cli
npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ npm install -g @mermaid-js/mermaid-cli
+ ~~~
    + CategoryInfo          : ObjectNotFound: (npm:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Thoughts?

**Comment by dinocaputo** [comment]
PowerShell session needs a restart in between installing node.js and mermaid.  Works fine after that.

**Comment by mozziemozz** [comment]
Thanks @dinocaputo I've added the hint to the Readme in the DEV branch. Will merge it into main when I'm confident enough that the new dev stuff is working fine.
