### ISSUE TITLE
Multiple Prompts for Authentication and Security Warnings

### ISSUE THREAD

**Issue by dinocaputo** [mozziemozz/M365CallFlowVisualizer#33]
Is it normal to be prompted multiple times for security warnings even though I have unblocked all the .ps files in the script directory and set the execution policy accordingly?  Also repeatedly get prompted for authentication even though I connect to teams and graph with appropriate accountID.  Modern auth window prompts me to sign in dozens of times repeatably. 

I can connect to graph using Connect-Graph -Scopes User.ReadWrite.All, Organization.Read.All  with no errors however see this repeatedly in the PowerShell execution

Get-MgGroup : Insufficient privileges to complete the operation.  

My understanding was that User.ReadWrite.All, Organization.Read.All was all that was required.  
Happy to provide more details if required.

**Comment by mozziemozz** [comment]
Hi Dino,

Have you been switching Tenants a lot? E.g. establishing graph connections to different tenants?
I have had the same issue a couple of months ago, where I got the repeated sign in prompts.

I added some stuff to the Connect-M365CFV function to handle this. I haven't had this issue anymore since then. The function should clear the local graph cache, if issues occur. Please also try a manual `Disconnect-MgGraph` in the active PS window.

Please try to use `Get-MgContext` to check if you're signed into the right tenant.
Are you running the script with PowerShell or from within VS Code integrated terminal?

Only these two scopes are required:

`Connect-MgGraph -Scopes "User.Read.All","Group.Read.All"`

Security warnings look like it's specific to your pc/config. Works fine for me.

**Comment by dinocaputo** [comment]
Yeah I'm in multiple tenants all the time.  But I used a fresh PS session and connect to graph using the tenantID to avoid these issues.  Unblock-file *.* runs but doesn't seem to unblock the files as I get prompted to run each script that is called.

**Comment by dinocaputo** [comment]
Get-MGUser on its own works fine allow I get prompted with modern auth every single time I run it.  It does return users.

**Comment by mozziemozz** [comment]
The Connect-M365CFV Function already uses the TenantId it gets from Connect-MicrosoftTeams. I tried to avoid issues like these but sometimes it can get messed up somehow.

The function tries to delete this folder: $env:USERPROFILE\.graph to clear the cache. I believe it doesn't matter if you're using a fresh PS session, if there's something there...

**Comment by dinocaputo** [comment]
Still facing the multiple prompts issue and I think its causing possible lockouts as eventually after 10 auth prompts I get can't sign in user.  Happy to work with you to try and resolve

**Comment by dinocaputo** [comment]
After manually clearing the contents of  $env:USERPROFILE.graph the behavior is better!
I am encountering a 

Syntax error in graph
mermaid version 9.3.0

for some call flows.  Not sure if it because of an unsupported feature. Checking your docs.

**Comment by mozziemozz** [comment]
Ok, maybe there's an issue with clearing the cache in my script. Or it's related to the local permissions. Mermaid Syntax Error is most likely due to a special character in names or in TTS greetings. If you paste the mermaid code on https://mermaid.live you should be able to see which one it is.

**Comment by dinocaputo** [comment]
I am using holiday schedules that call to external PSTN numbers so I believe that is not supported.  
I tried pasting the HTML and .md code into mermaid reports no diagram type detected.  What am I doing wrong?

**Comment by mozziemozz** [comment]
No that shouldn't be a problem at all. you have to include flowchart TB. Maybe try to use -DocType Mermaid so you'll get a plain mermaid output without the mermaid code block for markdown.

**Comment by dinocaputo** [comment]
Found the issue.  Mermaid doesn't like apostrophes in the holiday names.  ie.  New Year's Day it did not like.

**Comment by mozziemozz** [comment]
ok thank's I'll add that to the Optimize-DisplayName function so it get's removed.

**Comment by dinocaputo** [comment]
Also, Mermaid does not like (brackets)  in the AA or CQ Names
For example, Sales (Option 1)

**Comment by mozziemozz** [comment]
Which version are you using? AA and CQ names should be handled/special characters should be removed. I think I've added that quite a while ago. Please provide an example (e.g. Screenshot of the diagram) where in the call flow you see an AA/CQ name with an error. (please remove the char so that the diagram renders)

**Comment by dinocaputo** [comment]
Using version 2.8.5 - once I remove the ( ) from the Teams AA and CQ it renders so mermaid didn't like the ( )

**Comment by mozziemozz** [comment]
Yes, anything that's part of mermaid syntax can't be used inside of a mermaid node. There's a function in my script which should remove the brackets and other special chars. Weird that it doesn't work in your case. Can you tell me what the name of your AA or CQ looks like so I can try and repro in my tenant?

**Comment by dinocaputo** [comment]
Last one after some extensive testing with over 25+ AAs and 50+ CQs.  
Dashes in CQ names like "Call Queue - Main" are not supported neither.  removing it in Teams fixes.

**Comment by mozziemozz** [comment]
It looks like dashes are no problem in mermaid.live / mermaid.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/50239556/210104045-67a7b7ba-9d32-48cf-81eb-bde93cec2fa6.png">
It also renders in the htm file:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/50239556/210104065-281121b6-b758-4b04-b3db-5d0d8bc99cdc.png">
May I ask you to try the version from the DEV branch? I fixed something related to this issue in 2.8.7:
"|28.11.2022|M365CallFlowVisualizerV2.ps1|2.8.7|Fix bug / add Optimize-Displayname for auto attendant default and after hours call flow nodes.|"

But I'm still working on some other stuff, so I don't want to merge them into the main branch yet. Thanks.
AA containing a hyphen does not work for me in 2.8.5 but it does in 2.8.7b (latest published in DEV).

**Comment by dinocaputo** [comment]
I could but have already fixed the offending issues in Teams.  Let me try and revert one and will get back to you
