### ISSUE TITLE
Parameter passing erroring out

### ISSUE THREAD

**Issue by dinocaputo** [mozziemozz/M365CallFlowVisualizer#35]
![image](https://user-images.githubusercontent.com/32268083/219774430-f180f094-2f32-4bbd-abce-7134ae567b08.png)
How are the parameters expected?  Tried a few ways and it errors out.

**Comment by mozziemozz** [comment]
ShowPhoneNumberType is a switch, so you don't have to add $true. Just add -ShowPhoneNumberTrue.

   -ShowPhoneNumberType
        Specifies whether or not the phone number type of phone numbers should be displayed. (CallingPlan, OperatorConnect, DirectRouting)
        Required:           false
        Type:               switch
        Default value:      false

All params are explained/defined in the synopsis.

**Comment by dinocaputo** [comment]
Yeah this worked.  Showed True/False in readme so assumed all parameters required them.  
![image](https://user-images.githubusercontent.com/32268083/219783797-980f44c4-5380-4da7-b1d2-f5de29e307e5.png)

**Comment by mozziemozz** [comment]
Yeah some params are switches, some are bools because I want a default value for those. Not that uncommon for PowerShell I think.

I don't recall adding any of the new params to the readme but all should be in the synopsis.

You can always create a parent script which just calls the visualizer with your preferred params. ☺️

**Comment by dinocaputo** [comment]
Thanks all good.  Any way to run this once and capture ALL callflows in one run session?  The reason I ask is that if I run each AA as separate cmdlet it will read all AA's and CQs into an array and it slows down the processing.

**Comment by mozziemozz** [comment]
The script can only run for 1 top level app at a time but there is now a param called CacheResults which is false by default. So try to use -CacheResults $true. It will get all AAs, CQs and RAs and store them in Global variables, so for the next run, it will only need to lookup the stuff it has to, which all should be graph requests with an explicit ID (users/groups) as long as the PS session persists. But it won't read all voice apps again.
