### ISSUE TITLE
Unable to run .\M365CallFlowVisualizerV2.ps1

### ISSUE THREAD

**Issue by JGorgacz** [mozziemozz/M365CallFlowVisualizer#46]
Unable to run .\M365CallFlowVisualizerV2.ps1

For some reason it is not able to see the Function sections of the Github repository it seems like?

PS C:\Scripts> .\M365CallFlowVisualizerV2.ps1
. : The term '.\Functions\Connect-M365CFV.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:427 char:3
+ . .\Functions\Connect-M365CFV.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Connect-M365CFV.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Read-BusinessHours.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:428 char:3
+ . .\Functions\Read-BusinessHours.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Read-BusinessHours.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Optimize-DisplayName.ps1' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:429 char:3
+ . .\Functions\Optimize-DisplayName.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Optimize-DisplayName.ps1:String) [], CommandNotFoundExcepti
   on
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-TeamsUserCallFlow.ps1' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:430 char:3
+ . .\Functions\Get-TeamsUserCallFlow.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get-TeamsUserCallFlow.ps1:String) [], CommandNotFoundExcept
   ion
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-MsSystemMessage.ps1' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:431 char:3
+ . .\Functions\Get-MsSystemMessage.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get-MsSystemMessage.ps1:String) [], CommandNotFoundExceptio
   n
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-AccountType.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:432 char:3
+ . .\Functions\Get-AccountType.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get-AccountType.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\New-VoiceAppUserLinkProperties.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:433 char:3
+ . .\Functions\New-VoiceAppUserLinkProperties.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\New...kProperties.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-SharedVoicemailGroupMembers.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:434 char:3
+ . .\Functions\Get-SharedVoicemailGroupMembers.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get...roupMembers.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-IvrTransferMessage.ps1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:435 char:3
+ . .\Functions\Get-IvrTransferMessage.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get-IvrTransferMessage.ps1:String) [], CommandNotFoundExcep
   tion
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-AutoAttendantDirectorySearchConfig.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:436 char:3
+ . .\Functions\Get-AutoAttendantDirectorySearchConfig.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get...earchConfig.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-AllVoiceAppsAndResourceAccounts.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:437 char:3
+ . .\Functions\Get-AllVoiceAppsAndResourceAccounts.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get...rceAccounts.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Get-AllVoiceAppsAndResourceAccountsAppAuth.ps1' is not recognized as the name of a cmdlet,
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:438 char:3
+ . .\Functions\Get-AllVoiceAppsAndResourceAccountsAppAuth.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Get...untsAppAuth.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\SecureCredsMgmt.ps1' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:439 char:3
+ . .\Functions\SecureCredsMgmt.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\SecureCredsMgmt.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term '.\Functions\Connect-MsTeamsServicePrincipal.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:440 char:3
+ . .\Functions\Connect-MsTeamsServicePrincipal.ps1
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Functions\Con...cePrincipal.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

. : The term 'Connect-M365CFV' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:482 char:7
+     . Connect-M365CFV
+       ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-M365CFV:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: There is currently a bug in MicrosoftTeams PowerShell. Auto attendants are likely to output 'Male' as VoiceId
property when queried via PowerShell.
Please call your auto attendant's phone number to confirm the voice Id it's using. Use the -OverrideVoiceIdToFemale
switch param to change all 'Male' values to 'Female' in diagram output.
. : The term 'Get-AllVoiceAppsAndResourceAccounts' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\Scripts\M365CallFlowVisualizerV2.ps1:579 char:7
+     . Get-AllVoiceAppsAndResourceAccounts
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AllVoiceAppsAndResourceAccounts:String) [], CommandNotFoundExceptio
   n
    + FullyQualifiedErrorId : CommandNotFoundException

WARNING: No voice app was selected. The script cannot work it's magic until you select a top-level voice app.
Do you want to abort the script? [Y] = Yes or [N] = No: Y
Script aborted!

**Comment by mozziemozz** [comment]
It looks like you're running the script from `C:\Scripts\M365CallFlowVisualizerV2.ps1` which makes me think you only downloaded the main script? You need the entire repository and it needs the same hierarchy as the repo. Then you need to call M365CallFlowVisualizerV2.ps1 from the root folder.

E.g.

Clone or unzip the repo in C:\Scripts\M365CallFlowVisualizer
Make sure you see all scripts and folders, including \Functions

Run .\M365CallFlowVisualizerV2.ps1 from C:\Scripts\M365CallFlowVisualizer folder

**Comment by JGorgacz** [comment]
Thanks so much.  That was it!
