### ISSUE TITLE
MSOL Module is deprecated

### ISSUE THREAD

**Issue by DEberhardt** [mozziemozz/M365CallFlowVisualizer#5]
Hello,

I am using AzureAd (AzureAdPreview to be precise) - yes, I know, this one too is on its way out, but I try to stay away from MSOL as best as I can.

Assuming to run this in a connected environment, would you make it more generic to be able to use either (`Get-AzureAdUser -ObjectId $Operator.Id` instead of `Get-MsolUser $Operator.Id`)?

Cheers,
David

**Comment by mozziemozz** [comment]
Hi,

As described in the readme, under Planned Feature updates, I'm planning to migrate MSOL to MS Graph PowerShell.

> Migrate from MSOnline to Microsoft Graph PowerShell

https://github.com/mozziemozz/M365CallFlowVisualizer#planned-feature-updates

**Comment by DEberhardt** [comment]
Apologies, didn't read that far down :)

**Comment by mozziemozz** [comment]
No worries. 😊

**Comment by mozziemozz** [comment]
@DEberhardt MSOnline Cmdlets have now been replaced by Microsoft.Graph Cmdlets in V 2.4.0

**Comment by DEberhardt** [comment]
that was quick :) - I'll have a look, might learn something (haven't done much with the Graph ones yet as they were only scratching the surface)

**Comment by mozziemozz** [comment]
It was easier than I anticipated. Haven't used it much either but I figured why not use the latest technology if I have to do it anyway. I think MS has even some migration paths for complex scripts. In my script there were only 14 MSOL Cmdlets so it was pretty straight forward. You just have to grant consent the first time you connect.
