### ISSUE TITLE
Sequential numbering of Queues>Groups and Groups>Agents under set conditions.

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#7]
Consider adding sequential numbering on the line between:
- From Groups (you called them Agent-Lists) down to the Agents
- From Queue to the Groups (or direct-assigned-users to the queue)

This diagram gives you both examples of where sequential numbering is actually used 
![image](https://user-images.githubusercontent.com/38080190/149315802-cb9b7297-a4b9-4bdc-afec-fd3ceff096ba.png)

Pay close attention to the routing-mode assigned to the queue, and where the numbered-arrows are below.

**Comment by mozziemozz** [comment]
Thanks for sharing this diagram. I might start by adding the numbers on the links. But I think in a more sophisticated version, I'll add a node with the configured alert time between each agent. Is this diagram for an SfB or Teams environment? Just asking because all of the alert times and timeouts specified are not even possible in Teams.

**Comment by mozziemozz** [comment]
Ok turns out adding numbers to the links was fairly easy, if the routing method is serial.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/50239556/149394457-c39d40cd-c8a4-4329-ab44-4b65459687ec.png">

**Comment by sjackson0109** [comment]
This is definitely an MS Teams configuration, all built using powershell. And the timers were tweaked.

I noticed after sharing the diagram the ‘Reception Queue’ timer.. we had a support ticket for that, and we adjusted the ‘agent ring timer’ to 10s, online with the overflow.

If you do any of this via the GUI, all the attributes are visible, but setting call-timeout to anything lower than 15s is not possible.  Works fine via powershell.

**Comment by sjackson0109** [comment]
Did I mistake ‘attendant’ for ‘serial’ in my description and diagram?

**Comment by mozziemozz** [comment]
I just tried to set the agent alert time to 10s  or setting timeout threshold to 40s with PowerShell. Got the following errors/warnings:

`Set-CsCallQueue -Identity $cq.Identity -AgentAlertTime 10
Set-CsCallQueue : Agent alert time out of bound; agent alert time must be greater than or equal to (15) and less than or equal to (180). Please give correct parameter value.`

Same for Timeout threshold:
`Set-CsCallQueue -Identity $cq.Identity -TimeoutThreshold 40
WARNING: TimeoutThreshold must be a multiple of 15. TimeoutThreshold has been set to 45 seconds.`


> Did I mistake ‘attendant’ for ‘serial’ in my description and diagram?

What do you mean by that?

**Comment by mozziemozz** [comment]
> Did I mistake ‘attendant’ for ‘serial’ in my description and diagram?

So you have a Queue with 2 groups as agent list, but the routing method is attendant. This means that the call will ring for all agents at the same time, regardless of the group they're in. All members of the group which are EV enabled, will be added to the queue's Agent List. From my understanding, you can only change the order of the agents, if you use direct user assignments.

I added an M365 Group to the agent list. Here's the order it appears in M365:
![image](https://user-images.githubusercontent.com/50239556/149470447-2c6cbadc-44ca-44dd-b315-c1b714b72adb.png)

Same for AAD:
<img width="130" alt="image" src="https://user-images.githubusercontent.com/50239556/149464564-379963cf-f43f-40d1-84b0-310eed6bbada.png">

But if i query the AgentList of the queue, it's actually Wendy who's on top.
`$cq.Agents        


ObjectId                             OptIn
--------                             -----
fa19b242-8bae-419d-a4eb-12796577c81f  True
76606d0b-4d28-4246-9c08-2a0f95f96141  True


PS C:\Temp\M365CallFlowVisualizer> Get-MgUser -UserId fa19b242-8bae-419d-a4eb-12796577c81f


Id                                   DisplayName   Mail             UserPrincipalName UserType
--                                   -----------   ----             ----------------- --------
fa19b242-8bae-419d-a4eb-12796577c81f Wëndy Rhoades wendy@domain.ch wendy@mozzism.ch`



So, the numbered links on a queue with Attendant routing don't make sense to me. All Agents from all groups will be added to the queue's agent list and they will all receive the call at the same time.
From my perspective, it's best if you only have 1 group assigned per queue and overflow to the next queue which has another group assigned.

Anyway, in either case, the call flow is correctly displayed with my tool. I always read the queues agents from the queue's AgentList which means that it will include, Groups and Direct Assignments. For attendant routing, it doesn't matter if there are multiple groups assigned. For Serial routing, the order of the agent list will be relevant.

**Comment by sjackson0109** [comment]
Perhaps they added conditions in the MSTeams powershell module.  Never mind.. 15s intervals.
