### ISSUE TITLE
Error with Find-Holidays, when none-set in the auto-attendant

### ISSUE THREAD

**Issue by sjackson0109** [mozziemozz/M365CallFlowVisualizer#8]
PS U:\> U:\Teams\M365CallFlowVisualizerV2.ps1
Warning: Some versions of the 'MicrosoftTeams' Module can take a very long time to load, especially in IDEs like VS Code. Give it a few minutes before cancelling.
WARNING:  Distribution Lists or Users are added to callqueue but there are no eligible agents.
WARNING:  Distribution Lists or Users are added to callqueue but there are no eligible agents.
WARNING:  Distribution Lists or Users are added to callqueue but there are no eligible agents.
WARNING:  Distribution Lists or Users are added to callqueue but there are no eligible agents.
WARNING:  Distribution Lists or Users are added to callqueue but there are no eligible agents.
WARNING:  No Distribution Lists or Users added to callqueue. There will be no agents to call.
WARNING:  No Distribution Lists or Users added to callqueue. There will be no agents to call.
WARNING:  No Distribution Lists or Users added to callqueue. There will be no agents to call.
Find-Holidays : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:1911 char:37
+         . Find-Holidays -VoiceAppId $VoiceApp.Identity
+                                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-Holidays], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-Holidays
 
Find-AfterHours : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:1912 char:39
+         . Find-AfterHours -VoiceAppId $VoiceApp.Identity
+                                       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-AfterHours], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-AfterHours
 
You cannot call a method on a null-valued expression.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2082 char:36
+ ... ntent -Path "$FilePath\$(($VoiceAppFileName).Replace(" ","_"))_CallFl ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
Mermaid code copied to clipboard. Paste it on https://mermaid.live

**Comment by sjackson0109** [comment]
I can confirm the holidays exist globally within the tenant; but are not assigned (yet) to this call-flow. Am waiting for the spoken text to be confirmed by the client before applying them.

**Comment by mozziemozz** [comment]
First of all, which Version of the Script are you using?
Can you please share the Parameters you used to call the script? (You can, of course, asterisk sensitive data...)
Are you using the Grid-View to select one, using -VoiceAppName (and VoiceAppType) or -Identity?

> Find-AfterHours : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.

Everytime an AA is involved, the script first checks for the current AAs holiday. In your case, however, the error appears before it can check if the AA has holidays because the Identity of the AA to check is missing.

Is this a top level AA or a nested one?

**Comment by sjackson0109** [comment]
v 2.3.2

**Comment by sjackson0109** [comment]
the command console (entire window) was given above.. there were no input arguments, just the GUI prompt, where i manually selected the offending call-flow.

**Comment by mozziemozz** [comment]
Please download the newest release. 2.4.9. I can't reproduce it with this version. Tenant has holidays, AA has not. Running without parameters and selecting AA from the Grid-View. Runs without any errors. You might want to check out other new stuff since 2.3.2... you can now also export and link greeting audio files etc.

**Comment by sjackson0109** [comment]
I had updated Microsoft.Graph - and this issue goes away.

closing

**Comment by sjackson0109** [comment]
This is still an issue with your latest version.

ORG has a dozen holiday-schedules setup; spanning multiple countries.
This specific AA does NOT have any Holiday-Schedules assigned.


PS U:\Teams\Diagrams> U:\Teams\M365CallFlowVisualizerV2.ps1 -VoiceAppName 'COMPANYNAME - Intercom' -VoiceAppType 'Auto Attendant' -ShowTTSGreetingText -CustomFilePath U:\Teams\Diagrams
Connected Teams Tenant: ORGNAME
Connected Graph TenantId matches connected Teams TenantId.
Find-Holidays : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2807 char:37
+         . Find-Holidays -VoiceAppId $VoiceApp.Identity
+                                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-Holidays], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-Holidays
 
Find-AfterHours : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2808 char:39
+         . Find-AfterHours -VoiceAppId $VoiceApp.Identity
+                                       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-AfterHours], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-AfterHours
 
You cannot call a method on a null-valued expression.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2998 char:36
+ ... ntent -Path "$FilePath\$(($VoiceAppFileName).Replace(" ","_"))_CallFl ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At U:\Teams\M365CallFlowVisualizerV2.ps1:3031 char:53
+ ... -Replace "VoiceAppNameHtmlIdPlaceHolder",($($VoiceAppFileName).Replac ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

PS U:\Teams\Diagrams>

**Comment by sjackson0109** [comment]
I also have the exact same error for another auto-attendant, that DOES have 3x Holiday Schedules assigned.


U:\Teams\M365CallFlowVisualizerV2.ps1 -VoiceAppName 'COMPANYNAME - Reception' -VoiceAppType 'Auto Attendant' -ShowTTSGreetingText -CustomFilePath U:\Teams\Diagrams
Connected Teams Tenant: ORGNAME
Connected Graph TenantId matches connected Teams TenantId.
Find-Holidays : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2807 char:37
+         . Find-Holidays -VoiceAppId $VoiceApp.Identity
+                                     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-Holidays], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-Holidays
 
Find-AfterHours : Cannot bind argument to parameter 'VoiceAppId' because it is an empty string.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2808 char:39
+         . Find-AfterHours -VoiceAppId $VoiceApp.Identity
+                                       ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Find-AfterHours], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Find-AfterHours
 
You cannot call a method on a null-valued expression.
At U:\Teams\M365CallFlowVisualizerV2.ps1:2998 char:36
+ ... ntent -Path "$FilePath\$(($VoiceAppFileName).Replace(" ","_"))_CallFl ...
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 
You cannot call a method on a null-valued expression.
At U:\Teams\M365CallFlowVisualizerV2.ps1:3031 char:53
+ ... -Replace "VoiceAppNameHtmlIdPlaceHolder",($($VoiceAppFileName).Replac ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
 

PS U:\Teams\Diagrams>

**Comment by sjackson0109** [comment]
Confirmed Version: 2.5.5

**Comment by mozziemozz** [comment]
Can you confirm that the Name of the AA is 100% correct? Remember, this is the Name of the AA or CQ and NOT the display name of a resource account.

Find-Holidays and Find-AfterHours are the first functions which get called, after Get-CallFlow has been executed to determine the Identity of the Voice App. You can also run the script and pass the Identity of the AA or CQ directly by using:

`.\M365CallFlowVisualizerV2.ps1 -Identity "6fb84b40-f045-45e8-8c1a-8fc18188exxx"`

The only way I can reproduce this is by purposely entering a fasle name of the Voice App as parameter:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/50239556/153130946-185996a9-747c-49d7-95f6-26612d0e55e3.png">

I also tested an AA which doesn't have any linked holidays. It doesn't matter if the tenant has holidays or not. `Get-CsOnlineSchedule` is never used in the script. The script only works with data returned by `Get-CsAutoAttendant`

**Comment by sjackson0109** [comment]
You may have been correct.  
I copied the name from a MS Word document list (good old EM dash vs EN dash problem).

Copying from the MS Teams AA view - the call-flow builds with no issues.
